#!/command/with-contenv bash
# shellcheck shell=bash

# Load Generic Libraries
. /defaults/scripts/env.sh
. /defaults/scripts/liblog.sh
. /defaults/scripts/libredis.sh

echo "$info ==> -- Starting Redis setup --"

# Check the value of the ALLOW_EMPTY_PASSWORD environment variable
case "$ALLOW_EMPTY_PASSWORD" in
    "yes")
    EMPTY_PASSWORD=true
    ;;
    "no")
    EMPTY_PASSWORD=false
    ;;
  *)
    echo "$warn ==> Error: Invalid value for ALLOW_EMPTY_PASSWORD: $ALLOW_EMPTY_PASSWORD. Please set it to either 'yes' or 'no'"
    exit 1
    ;;
esac

# Check if REDIS_PASSWORD is set
if [ -n "$REDIS_PASSWORD" ]; then
    if [ "$EMPTY_PASSWORD" = false ]; then
        redis_conf_set requirepass "$REDIS_PASSWORD"
        redis_conf_set protected-mode yes
    else
        echo "$warn ==> Please set ALLOW_EMPTY_PASSWORD=no"
        redis_conf_unset requirepass
        exit 1
    fi
else
    if [ "$EMPTY_PASSWORD" = false ]; then
        echo "$warn ==> Please set REDIS_PASSWORD or set ALLOW_EMPTY_PASSWORD=yes"
        redis_conf_unset requirepass
        exit 1
    else
        echo "$warn ==> Redis running with ALLOW_EMPTY_PASSWORD=yes consider set REDIS_PASSWORD!"
        redis_conf_set protected-mode no
    fi
fi

# copy local redis-local.conf if it doesn't exist
echo "$info ==> Setting Redis config file"
if [[ ! -f /config/redis/redis-local.conf ]]; then
    cp /defaults/redis/redis-local.conf /config/redis/redis-local.conf
fi

# Check if the EXTRA_FLAGS environment variable is set
if [ -n "$EXTRA_FLAGS" ]; then
    # Create or read the Redis local configuration file
    redis_local_config="/config/redis/redis-local.conf"

    # Store the key-value pairs from the EXTRA_FLAGS environment variable
    EXTRA_FLAGS="$EXTRA_FLAGS"

    # Split the EXTRA_FLAGS variable into key-value pairs using whitespace as the delimiter
    IFS=' ' read -ra EXTRA_FLAGS_ARRAY <<< "$EXTRA_FLAGS"

    # Read the existing keys from the Redis local configuration file
    existing_keys=($(awk '{print $1}' "$redis_local_config"))

    # Delete keys from the configuration file if they are not in the EXTRA_FLAGS environment variable
    for existing_key in "${existing_keys[@]}"; do
    if [[ "${EXTRA_FLAGS}" != *"--$existing_key "* ]]; then
        sed -i "/^$existing_key /d" "$redis_local_config"
        echo "$info ==> Deleted Extra Flags $existing_key from $redis_local_config."
    fi
    done

    # Loop through the key-value pairs in EXTRA_FLAGS and append new keys and values
    key=""
    for item in "${EXTRA_FLAGS_ARRAY[@]}"; do
    if [[ "$item" == "--"* ]]; then
        # Remove leading "--" from the key
        key="${item:2}"
    elif [ -n "$key" ]; then
        value="$item"
        # Check if the key already exists in the Redis local configuration file
        if grep -q "^$key " "$redis_local_config"; then
        echo "$info ==> Extra Flags $key already exists in $redis_local_config. Skipping..."
        else
        # Append the key and value to the Redis local configuration file
        echo "$key $value" >> "$redis_local_config"
        echo "$info ==> Added Extra Flags $key with value $value to $redis_local_config."
        fi
        key=""
    fi
    done
    
else
    echo "$info ==> No EXTRA_FLAGS env defined"
fi

# copy user redis-local.conf to image
cp /config/redis/redis-local.conf /etc/redis/redis-local.conf

echo "$info ==> -- Redis setup finished! --"